# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bf195c954796e4fd172cb0a950d01c5762e3c76eddc4d3a86c0b9b8d9f9ee0561cceb547ec83d4155b749a6fb88ece92d993580d2ea12c2c15b6c04ea55948b

test:
  secret_key_base: c5e5b6cb36eb6ec6aeb7011485ae12dc7d68a361ec4c0677f0b7228ec9faa750563f5e5d056c8cfdd76b7fd0441a97232cd9cd34d34931c1d0efffc36cb79ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
